Repository AY2223S2-CS2103T-F12-2/tp, pull requests merged in 2023-03, with the labels that each got.

#35 Fix minor grammar mistake in UserGuide.md
  docs/UserGuide.md
Labels: documentation

#37 Modify UserGuide.md to adapt to specifications for CoDoc
  docs/UserGuide.md
Labels: documentation

#47 [GUI] Add working right panel as InfoPanel and basic support for view command
  README.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ProfilePicture.java
  src/main/java/seedu/address/ui/infopanel/DetailedContact.java
  src/main/java/seedu/address/ui/infopanel/DetailedInfo.java
  src/main/java/seedu/address/ui/infopanel/DetailedModule.java
  src/main/java/seedu/address/ui/infopanel/DetailedSkill.java
  src/main/java/seedu/address/ui/infopanel/InfoTab.java
  src/main/resources/view/DetailedContact.fxml
  src/main/resources/view/DetailedModule.fxml
  src/main/resources/view/DetailedSkill.fxml
  src/main/resources/view/InfoTab.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High

#56 Make Phone and Address parameters optional
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/infopanel/InfoTab.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: priority.High

#58 Change Phone to GitHub
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/Ui.png
  docs/team/anchengyang.md
  docs/team/harin0826.md
  docs/team/linustws.md
  docs/team/nappysprout.md
  docs/team/shawnyip-au.md
  src/main/java/codoc/logic/commands/AddCommand.java
  src/main/java/codoc/logic/commands/EditCommand.java
  src/main/java/codoc/logic/parser/AddCommandParser.java
  src/main/java/codoc/logic/parser/CliSyntax.java
  src/main/java/codoc/logic/parser/EditCommandParser.java
  src/main/java/codoc/logic/parser/ParserUtil.java
  src/main/java/codoc/model/person/Github.java
  src/main/java/codoc/model/person/Person.java
  src/main/java/codoc/model/person/Phone.java
  src/main/java/codoc/model/util/SampleDataUtil.java
  src/main/java/codoc/storage/JsonAdaptedPerson.java
  src/main/java/codoc/ui/PersonCard.java
  src/main/java/codoc/ui/UiManager.java
  src/main/resources/images/technologist.png
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonCodocStorageTest/invalidAndValidPersonCodoc.json
  src/test/data/JsonCodocStorageTest/invalidPersonCodoc.json
  src/test/data/JsonSerializableCodocTest/duplicatePersonCodoc.json
  src/test/data/JsonSerializableCodocTest/invalidPersonCodoc.json
  src/test/data/JsonSerializableCodocTest/typicalPersonsCodoc.json
  src/test/java/codoc/commons/util/AppUtilTest.java
  src/test/java/codoc/logic/LogicManagerTest.java
  src/test/java/codoc/logic/commands/CommandTestUtil.java
  src/test/java/codoc/logic/commands/EditCommandTest.java
  src/test/java/codoc/logic/commands/EditPersonDescriptorTest.java
  src/test/java/codoc/logic/parser/AddCommandParserTest.java
  src/test/java/codoc/logic/parser/CodocParserTest.java
  src/test/java/codoc/logic/parser/EditCommandParserTest.java
  src/test/java/codoc/logic/parser/ParserUtilTest.java
  src/test/java/codoc/model/person/GithubTest.java
  src/test/java/codoc/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/codoc/model/person/PersonTest.java
  src/test/java/codoc/model/person/PhoneTest.java
  src/test/java/codoc/storage/JsonAdaptedPersonTest.java
  src/test/java/codoc/testutil/EditPersonDescriptorBuilder.java
  src/test/java/codoc/testutil/PersonBuilder.java
  src/test/java/codoc/testutil/PersonUtil.java
  src/test/java/codoc/testutil/TypicalPersons.java
Labels: priority.High

#66 Edit command
  src/main/java/codoc/logic/LogicManager.java
  src/main/java/codoc/logic/commands/AddCommand.java
  src/main/java/codoc/logic/commands/EditCommand.java
  src/main/java/codoc/logic/parser/AddCommandParser.java
  src/main/java/codoc/logic/parser/CliSyntax.java
  src/main/java/codoc/logic/parser/CodocParser.java
  src/main/java/codoc/logic/parser/EditCommandParser.java
  src/main/java/codoc/model/person/Person.java
  src/main/java/codoc/model/person/UniquePersonList.java
  src/test/data/JsonSerializableCodocTest/duplicatePersonCodoc.json
  src/test/data/JsonSerializableCodocTest/typicalPersonsCodoc.json
  src/test/java/codoc/logic/LogicManagerTest.java
  src/test/java/codoc/logic/commands/CommandTestUtil.java
  src/test/java/codoc/logic/commands/EditCommandTest.java
  src/test/java/codoc/logic/parser/AddCommandParserTest.java
  src/test/java/codoc/logic/parser/CodocParserTest.java
  src/test/java/codoc/logic/parser/EditCommandParserTest.java
  src/test/java/codoc/model/person/PersonTest.java
  src/test/java/codoc/model/person/UniquePersonListTest.java
  src/test/java/codoc/testutil/EditPersonDescriptorBuilder.java
  src/test/java/codoc/testutil/PersonBuilder.java
  src/test/java/codoc/testutil/PersonUtil.java
  src/test/java/codoc/testutil/TypicalPersons.java
Labels: priority.High

#71 [GUI] Design update
  src/main/java/codoc/MainApp.java
  src/main/java/codoc/ui/infopanel/DetailedModule.java
  src/main/java/codoc/ui/infopanel/DetailedSkill.java
  src/main/java/codoc/ui/infopanel/InfoTab.java
  src/main/resources/font/JetBrainsMono-Bold.ttf
  src/main/resources/font/JetBrainsMono-ExtraBold.ttf
  src/main/resources/font/JetBrainsMono-ExtraLight.ttf
  src/main/resources/font/JetBrainsMono-Light.ttf
  src/main/resources/font/JetBrainsMono-Regular.ttf
  src/main/resources/font/JetBrainsMono-SemiBold.ttf
  src/main/resources/font/JetBrainsMono-Thin.ttf
  src/main/resources/font/RobotoMono_Bold.ttf
  src/main/resources/font/RobotoMono_Light.ttf
  src/main/resources/font/RobotoMono_Regular.ttf
  src/main/resources/font/Roboto_Bold.ttf
  src/main/resources/font/Roboto_Light.ttf
  src/main/resources/font/Roboto_Medium.ttf
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DetailedContact.fxml
  src/main/resources/view/DetailedModule.fxml
  src/main/resources/view/DetailedSkill.fxml
  src/main/resources/view/InfoTab.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ModuleListCard.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/SkillListCard.fxml
Labels: GUI

#72 [GUI] Implement more concise display for PersonListCard
  src/main/java/codoc/logic/commands/ViewCommand.java
  src/main/java/codoc/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
Labels: GUI

#82 Change find OR to AND and change finding of name, year, course to contains instead of containsword
  src/main/java/codoc/logic/parser/FindCommandParser.java
  src/main/java/codoc/model/module/ModuleContainsKeywordsPredicate.java
  src/main/java/codoc/model/person/CourseContainsKeywordsPredicate.java
  src/main/java/codoc/model/person/NameContainsKeywordsPredicate.java
  src/main/java/codoc/model/person/YearContainsKeywordsPredicate.java
  src/main/java/codoc/model/skill/SkillContainsKeywordsPredicate.java
  src/main/java/codoc/model/util/SampleDataUtil.java
Labels: priority.High

#83 uppercase all courses
  src/main/java/codoc/logic/commands/AddCommand.java
  src/main/java/codoc/model/person/Course.java
Labels: priority.Medium

#87 Edited error messages
  src/main/java/codoc/logic/commands/AddCommand.java
  src/main/java/codoc/logic/commands/EditCommand.java
  src/main/java/codoc/logic/commands/FindCommand.java
  src/main/java/codoc/logic/commands/ViewCommand.java
Labels: enhancement

#88 Person, course and edit command classes
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/CourseClassDiagram.puml
  docs/diagrams/EditActivityDiagram.puml
  docs/diagrams/EditSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/PersonClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/CourseClassDiagram.png
  docs/images/EditActivityDiagram.png
  docs/images/EditSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/PersonClassDiagram.png
  src/main/java/codoc/logic/commands/EditCommand.java
  src/main/java/codoc/logic/parser/AddCommandParser.java
  src/main/java/codoc/logic/parser/ParserUtil.java
  src/main/java/codoc/model/course/Course.java
  src/main/java/codoc/model/course/CourseList.java
  src/main/java/codoc/model/person/Person.java
  src/main/java/codoc/model/util/SampleDataUtil.java
  src/main/java/codoc/storage/JsonAdaptedPerson.java
  src/test/java/codoc/testutil/EditPersonDescriptorBuilder.java
  src/test/java/codoc/testutil/PersonBuilder.java
  src/test/java/codoc/testutil/PersonUtil.java
Labels: documentation

#95 Fix potential ui bug
  src/main/java/codoc/ui/infopanel/InfoTab.java
Labels: bug

#94 Change find for name, year, course to be AND for multiple keywords within the prefix
  src/main/java/codoc/model/person/CourseContainsKeywordsPredicate.java
  src/main/java/codoc/model/person/NameContainsKeywordsPredicate.java
  src/main/java/codoc/model/person/YearContainsKeywordsPredicate.java
  src/test/java/codoc/logic/commands/FindCommandTest.java
  src/test/java/codoc/model/person/NameContainsKeywordsPredicateTest.java
Labels: priority.High

#97 new help window text
  docs/DeveloperGuide.md
  src/main/java/codoc/ui/CommandExample.java
  src/main/java/codoc/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: enhancement

#98 Help window
  src/main/java/codoc/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: GUI

#99 Help window
  src/main/java/codoc/ui/HelpWindow.java
Labels: GUI

#92 Add github, linkedin, skills and find command details in DG
  docs/DeveloperGuide.md
  docs/diagrams/FindSequenceDiagram.puml
  docs/images/FindSequenceDiagram.png
  src/main/java/codoc/model/person/Person.java
Labels: documentation, priority.High

#103 Add scroll back to top
  docs/DeveloperGuide.md
Labels: documentation

#105 Reworking EditCommand and EditCommandParser
  src/main/java/codoc/logic/LogicManager.java
  src/main/java/codoc/logic/commands/EditCommand.java
  src/main/java/codoc/logic/parser/AddCommandParser.java
  src/main/java/codoc/logic/parser/CodocParser.java
  src/main/java/codoc/logic/parser/EditCommandParser.java
  src/main/java/codoc/logic/parser/ParserUtil.java
  src/test/java/codoc/logic/commands/CommandTestUtil.java
  src/test/java/codoc/logic/parser/CodocParserTest.java
  src/test/java/codoc/logic/parser/EditCommandParserTest.java
  src/test/java/codoc/logic/parser/ParserUtilTest.java
  src/test/java/codoc/testutil/EditPersonDescriptorBuilder.java
  src/test/java/codoc/testutil/PersonUtil.java
Labels: enhancement

#108 Developer Guide update for UI
  docs/DeveloperGuide.md
Labels: documentation

#120 add left panel for course list
  src/main/java/codoc/model/course/CourseList.java
  src/main/java/codoc/ui/CourseListPanel.java
  src/main/java/codoc/ui/MainWindow.java
  src/main/resources/view/CourseListPanel.fxml
  src/main/resources/view/MainWindow.fxml
Labels: enhancement, GUI

#122 some ui resizing fix
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonCard.fxml
Labels: bug

#123 Show Find History
  src/main/java/codoc/logic/commands/EditCommand.java
  src/main/java/codoc/logic/commands/FindCommand.java
  src/main/java/codoc/logic/commands/ListCommand.java
  src/main/java/codoc/logic/parser/FindCommandParser.java
  src/main/java/codoc/model/Model.java
  src/main/java/codoc/model/ModelManager.java
  src/main/java/codoc/model/module/ModuleContainsKeywordsPredicate.java
  src/main/java/codoc/model/person/CourseContainsKeywordsPredicate.java
  src/main/java/codoc/model/person/NameContainsKeywordsPredicate.java
  src/main/java/codoc/model/person/YearContainsKeywordsPredicate.java
  src/main/java/codoc/model/skill/SkillContainsKeywordsPredicate.java
  src/test/java/codoc/logic/commands/AddCommandTest.java
  src/test/java/codoc/logic/commands/CommandTestUtil.java
  src/test/java/codoc/logic/commands/DeleteCommandTest.java
  src/test/java/codoc/logic/commands/FindCommandTest.java
  src/test/java/codoc/model/ModelManagerTest.java
  src/test/java/codoc/model/skill/SkillContainsKeywordsPredicateTest.java
Labels: enhancement, GUI

#124 Add wrap text to result display
  src/main/java/codoc/ui/ResultDisplay.java
Labels: GUI

#125 empty person list display protagonist bug
  src/main/java/codoc/logic/commands/AddCommand.java
  src/main/java/codoc/logic/commands/DeleteCommand.java
  src/main/java/codoc/model/ModelManager.java
  src/main/java/codoc/model/course/CourseList.java
  src/main/java/codoc/model/person/Person.java
  src/main/java/codoc/ui/HelpWindow.java
  src/test/data/JsonSerializableCodocTest/typicalPersonsCodoc.json
  src/test/java/codoc/logic/commands/AddCommandTest.java
Labels: bug, enhancement

#126 Make module and skill listview extend when maximised
  src/main/resources/view/DetailedModule.fxml
  src/main/resources/view/DetailedSkill.fxml
Labels: GUI

#127 Show "Not Added" for empty github and linkedin. Rearranged order to have email on top (cos compulsory).
  src/main/java/codoc/ui/infopanel/DetailedContact.java
  src/main/resources/view/DetailedContact.fxml
Labels: GUI

#130 Remove ListView prefHeight calculation
  docs/DeveloperGuide.md
  src/main/java/codoc/ui/MainWindow.java
  src/main/java/codoc/ui/PersonCard.java
  src/main/java/codoc/ui/PersonListPanel.java
  src/main/java/codoc/ui/UiEventListener.java
  src/main/java/codoc/ui/infopanel/DetailedContact.java
  src/main/java/codoc/ui/infopanel/DetailedInfo.java
  src/main/java/codoc/ui/infopanel/DetailedModule.java
  src/main/java/codoc/ui/infopanel/DetailedSkill.java
  src/main/java/codoc/ui/infopanel/InfoTab.java
  src/main/resources/view/CourseListPanel.fxml
  src/main/resources/view/DetailedContact.fxml
  src/main/resources/view/DetailedModule.fxml
  src/main/resources/view/DetailedSkill.fxml
  src/main/resources/view/InfoTab.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonCard.fxml
Labels: documentation

#129 Enhancement of click feature
  src/main/java/codoc/ui/MainWindow.java
  src/main/java/codoc/ui/PersonCard.java
  src/main/java/codoc/ui/PersonListPanel.java
  src/main/java/codoc/ui/UiEventListener.java
  src/main/java/codoc/ui/infopanel/DetailedContact.java
  src/main/java/codoc/ui/infopanel/DetailedInfo.java
  src/main/java/codoc/ui/infopanel/DetailedModule.java
  src/main/java/codoc/ui/infopanel/DetailedSkill.java
  src/main/java/codoc/ui/infopanel/InfoTab.java
  src/main/resources/view/CourseListPanel.fxml
  src/main/resources/view/DetailedContact.fxml
  src/main/resources/view/DetailedModule.fxml
  src/main/resources/view/DetailedSkill.fxml
  src/main/resources/view/InfoTab.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonCard.fxml
Labels: GUI

#134 Developerguide
  docs/DeveloperGuide.md
  docs/diagrams/EditActivityDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/EditActivityDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/UiClassDiagram.png
  src/main/java/codoc/logic/commands/EditCommand.java
  src/main/java/codoc/logic/parser/CliSyntax.java
  src/main/java/codoc/logic/parser/EditCommandParser.java
Labels: documentation

#133 Click update and more ui fix
  src/main/resources/view/DetailedModule.fxml
  src/main/resources/view/DetailedSkill.fxml
  src/main/resources/view/PersonCard.fxml
Labels: enhancement, GUI

#135 Minor color fix for skills pane
  src/main/resources/view/DetailedSkill.fxml
Labels: GUI

#138 Add navigation, tutorial to UG
  docs/UserGuide.md
  docs/images/Ui-minimised.png
  docs/images/navigation.png
  docs/images/tutorial/adding-bob.png
  docs/images/tutorial/editing-bobs-modules.png
  docs/images/tutorial/finding-cs2103t.png
  docs/images/tutorial/viewing-bobs-modules.png
Labels: documentation

#139 Copy github and linkedin buttons
  src/main/java/codoc/ui/infopanel/DetailedContact.java
  src/main/resources/view/CodocTheme.css
  src/main/resources/view/DetailedContact.fxml
  src/main/resources/view/DetailedModule.fxml
  src/main/resources/view/DetailedSkill.fxml
Labels: enhancement, GUI

#141 Fix bug
  src/main/java/codoc/logic/parser/ParserUtil.java
  src/main/java/codoc/model/person/Github.java
  src/main/java/codoc/model/person/Linkedin.java
Labels: bug

#143 fix links in table of contents UG
  docs/UserGuide.md
Labels: documentation

#145 Modify view in tutorial
  docs/UserGuide.md
Labels: documentation

#146 Fix wording
  docs/UserGuide.md
Labels: documentation

#147 Remove profile pic path in result display after adding person
  src/main/java/codoc/model/person/Github.java
  src/main/java/codoc/model/person/Linkedin.java
  src/main/java/codoc/model/person/Person.java
Labels: bug

#148 add copy email button
  src/main/java/codoc/ui/infopanel/DetailedContact.java
  src/main/resources/view/DetailedContact.fxml
Labels: enhancement, GUI

#149 Userguide
  docs/UserGuide.md
  docs/images/UiViewIndex.jpg
  docs/images/UiViewModule.jpg
Labels: documentation

#150 Change screenshot of view command
  docs/images/UiViewIndex.jpg
Labels: documentation

#152 Update tutorials for User Guide
  docs/UserGuide.md
  docs/images/user-guide/download_codoc.PNG
Labels: documentation

#155 Add pictures to replace placeholders and update FAQ in User Guide.
  docs/UserGuide.md
  docs/images/user-guide/addcommand-bob.PNG
  docs/images/user-guide/install_home_folder.PNG
  docs/images/user-guide/open_done.PNG
  docs/images/user-guide/open_new_file.png
  docs/images/user-guide/open_rename.png
  docs/images/user-guide/open_rename_warning.PNG
  docs/images/user-guide/open_save_text.PNG
  docs/images/user-guide/viewcommand-bob.PNG
Labels: documentation

#160 Scroll to last person when added
  src/main/java/codoc/logic/commands/AddCommand.java
  src/main/java/codoc/logic/commands/CommandResult.java
  src/main/java/codoc/ui/MainWindow.java
  src/main/java/codoc/ui/PersonListPanel.java
Labels: enhancement

#161 [GUI] Auto-scroll and highlight for ViewCommand, name wrap fix, and new result message for copying URLs
  src/main/java/codoc/logic/commands/CommandResult.java
  src/main/java/codoc/logic/commands/ViewCommand.java
  src/main/java/codoc/ui/MainWindow.java
  src/main/java/codoc/ui/PersonListPanel.java
  src/main/java/codoc/ui/infopanel/DetailedContact.java
  src/main/java/codoc/ui/infopanel/DetailedInfo.java
  src/main/java/codoc/ui/infopanel/InfoTab.java
  src/main/resources/view/DetailedContact.fxml
  src/main/resources/view/DetailedModule.fxml
  src/main/resources/view/DetailedSkill.fxml
  src/main/resources/view/InfoTab.fxml
Labels: GUI, UI

#164 Update Developer Guide
  docs/DeveloperGuide.md
Labels: documentation

#163 Limit name length to 50 characters
  src/main/java/codoc/logic/parser/ParserUtil.java
Labels: enhancement
